# Generated by Django 4.2.11 on 2026-08-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Basic 1 (Class 1), JHS 2, SHS 3', max_length=100)),
                ('stage', models.CharField(choices=[('KG', 'Kindergarten'), ('PRIMARY', 'Primary (Basic 1-6)'), ('JHS', 'Junior High School (Basic 7-9)'), ('SHS', 'Senior High School'), ('OTHER', 'Other / Not GES-aligned')], default='OTHER', help_text='GES curriculum band this level belongs to -- used to align AI-generated exam questions with the correct NaCCA Standards-Based Curriculum content.', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for sorting')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='school.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('default_password', models.CharField(blank=True, help_text='The default password assigned when the student account was created', max_length=128, null=True)),
                ('face_encoding', models.JSONField(blank=True, help_text='Face encoding data for facial recognition (stored as JSON array)', null=True)),
                ('face_registered', models.BooleanField(default=False, help_text="Whether the student's face has been registered for recognition")),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile photo used for face recognition', null=True, upload_to='student_faces/%Y/%m/')),
                ('face_registered_at', models.DateTimeField(blank=True, help_text='When the face was last registered/updated', null=True)),
                ('address', models.TextField(blank=True, help_text='Residential address of the student', null=True)),
                ('contact_phone', models.CharField(blank=True, help_text="Student's direct phone number", max_length=20, null=True)),
                ('id_card_type', models.CharField(blank=True, choices=[('GHANA_CARD', 'Ghana Card'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport'), ('BIRTH_CERT', 'Birth Certificate'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('id_card_number', models.CharField(blank=True, help_text='Ghana Card / Voter ID / Passport number', max_length=50, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('face_registered_by', models.ForeignKey(blank=True, help_text="Who registered this student's face", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_faces', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.gradelevel')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='academics.schoolclass')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
