# Generated by Django 4.2.11 on 2026-08-28 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_history',
            field=models.JSONField(blank=True, default=list, help_text='Historical enrollment records'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_new_student',
            field=models.BooleanField(default=True, help_text="True if this is the student's first enrollment at the school"),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, help_text='Previous school if transfer student', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StudentEnrollmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('NEW', 'New Student'), ('RETURNING', 'Returning Student'), ('TRANSFER', 'Transfer Student')], max_length=50, unique=True)),
                ('code', models.CharField(choices=[('NEW', 'New Student'), ('RETURNING', 'Returning Student'), ('TRANSFER', 'Transfer Student')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('auto_prepare_fees', models.BooleanField(default=True)),
                ('auto_approve_fees', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_types', to='school.school')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_type',
            field=models.ForeignKey(blank=True, help_text='The enrollment type for this student (New, Returning, Transfer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.studentenrollmenttype'),
        ),
    ]
