# Generated by Django 4.2.11 on 2026-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo'),
        ('students', '0002_student_enrollment_history_student_is_new_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollmenttype',
            name='code',
            field=models.CharField(choices=[('NEW', 'New Student'), ('RETURNING', 'Returning Student'), ('TRANSFER', 'Transfer Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentenrollmenttype',
            name='name',
            field=models.CharField(choices=[('NEW', 'New Student'), ('RETURNING', 'Returning Student'), ('TRANSFER', 'Transfer Student')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollmenttype',
            unique_together={('school', 'code')},
        ),
    ]
