# Generated by Django 4.2.11 on 2026-08-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g., Mid-Term Mathematics Exam', max_length=200, null=True)),
                ('subject', models.CharField(help_text='e.g., Mathematics, Science', max_length=100)),
                ('assessment_type', models.CharField(choices=[('EXAM', 'Exam'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment')], max_length=15)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(blank=True, help_text='Which term this assessment counts toward - used by report card generation. If left blank, report cards fall back to matching by creation date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='school.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_achieved', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.assessment')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
