# Generated by Django 4.2.11 on 2026-09-03 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo'),
        ('assessments', '0003_terminal_results_score_component'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='terminalresult',
            new_name='assessments_school__449aee_idx',
            old_name='assessments_school_3f7d2c_idx',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='academic_term',
            field=models.ForeignKey(blank=True, help_text='Academic term for this assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='school.academicterm'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(help_text='e.g., End of Term Mathematics Examination', max_length=200, null=True),
        ),
    ]
