# Generated by Django 4.2.11 on 2026-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_repair_invalid_uuid_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='attendance_absent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_late',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='attendance_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='ca_weight',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='class_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='exam_weight',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='headteacher_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='next_term_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='overall_grade',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='overall_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='overall_remark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promotion_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='teacher_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='total_possible',
            field=models.FloatField(default=0),
        ),
    ]
