# Generated by Django 4.2.11 on 2026-09-04 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0005_report_comment_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcommentbatch',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_comment_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
