"""EduAI language translation gateway.

Design goals:
- Never use a general-purpose LLM as the first choice for Ga/Twi.
- Use a neural machine-translation provider for Ga/Twi.
- Keep Google Cloud Translation available as an optional Twi provider.
- Preserve names, numbers, URLs, IDs, dates, email addresses and template-like tokens.
- Fall back gracefully to the existing Groq gateway when a specialist provider is unavailable.

Environment variables:
    EDUAI_NLLB_API_URL=https://winstxnhdw-nllb-api.hf.space/api/v4/translator
    EDUAI_NLLB_TIMEOUT=45
    GOOGLE_TRANSLATE_API_KEY=<optional, Twi only>
    EDUAI_TRANSLATOR_TWI_PROVIDER=google|nllb

The NLLB endpoint is deliberately configurable. For production, EduAI can point
this setting at its own self-hosted NLLB/CTranslate2 service rather than relying
on a shared public endpoint.
"""

import re
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests
from django.conf import settings

from ai_engine.services.services import AIService


LANGUAGES = {
    "English": {"code": "en", "nllb": "eng_Latn"},
    "Twi": {"code": "ak", "nllb": "twi_Latn"},
    "Ga": {"code": "gaa", "nllb": "gaa_Latn"},
    "French": {"code": "fr", "nllb": "fra_Latn"},
    "Arabic": {"code": "ar", "nllb": "arb_Arab"},
}

MAX_TEXT_LENGTH = 4000
MAX_PAGE_TEXT_LENGTH = 16000
MAX_PAGE_ITEMS = 120
NLLB_DEFAULT_URL = "https://winstxnhdw-nllb-api.hf.space/api/v4/translator"

# Terms that must never be translated. This is intentionally a technical
# protection list, not a Ga/Twi dictionary. Language-specific terminology is
# generated by the specialist translation provider instead of an unverified
# hand-written word list.
PROTECTED_PATTERNS = [
    r"https?://[^\s]+",
    r"www\.[^\s]+",
    r"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}",
    r"\b[A-Z]{2,}[A-Z0-9_-]*\b",  # IDs/acronyms
    r"\b\d+(?:[.,:/-]\d+)*\b",  # dates, amounts, IDs, times
    r"\{\{.*?\}\}",
    r"\{%.*?%\}",
    r"\{#.*?#\}",
]


def _setting(name, default=""):
    return getattr(settings, name, None) or __import__("os").getenv(name, default)


def _normalise_language(value):
    value = (value or "English").strip()
    return value if value in LANGUAGES else "English"


def _protect(text):
    tokens = {}
    counter = 0

    def replace(match):
        nonlocal counter
        key = f"ZXQPROT{counter}QXZ"
        tokens[key] = match.group(0)
        counter += 1
        return key

    protected = text
    for pattern in PROTECTED_PATTERNS:
        protected = re.sub(pattern, replace, protected)
    return protected, tokens


def _restore(text, tokens):
    result = text or ""
    # A small number of model providers alter punctuation around placeholders.
    # Restore exact tokens first, then tolerate surrounding spaces.
    for key, original in tokens.items():
        result = result.replace(key, original)
        result = result.replace(key.lower(), original)
    return result


def _split_for_provider(text, max_chars=1800):
    """Split long text at sentence/line boundaries for NLLB."""
    if len(text) <= max_chars:
        return [text]
    pieces = []
    current = []
    size = 0
    for paragraph in re.split(r"(?<=\n)|(?<=[.!?])\s+", text):
        if not paragraph:
            continue
        if current and size + len(paragraph) + 1 > max_chars:
            pieces.append(" ".join(current).strip())
            current, size = [], 0
        current.append(paragraph)
        size += len(paragraph) + 1
    if current:
        pieces.append(" ".join(current).strip())
    return pieces or [text[:max_chars]]


def _google_twi(text):
    api_key = _setting("GOOGLE_TRANSLATE_API_KEY", "").strip()
    if not api_key:
        return None

    url = "https://translation.googleapis.com/language/translate/v2"
    response = requests.post(
        url,
        headers={"X-goog-api-key": api_key, "Content-Type": "application/json"},
        json={
            "q": [text],
            "source": "en",
            "target": "ak",
            "format": "text",
        },
        timeout=int(_setting("EDUAI_TRANSLATOR_TIMEOUT", "45")),
    )
    if not response.ok:
        return None
    data = response.json()
    values = ((data.get("data") or {}).get("translations") or [])
    return (values[0].get("translatedText") or "").strip() if values else None


def _nllb(text, target):
    url = (_setting("EDUAI_NLLB_API_URL", NLLB_DEFAULT_URL) or NLLB_DEFAULT_URL).strip()
    timeout = int(_setting("EDUAI_NLLB_TIMEOUT", "45"))
    response = requests.get(
        url,
        params={"text": text, "source": "eng_Latn", "target": target},
        timeout=timeout,
    )
    if not response.ok:
        return None

    data = response.json()
    # Support common NLLB/CTranslate2 API response shapes.
    if isinstance(data, str):
        return data.strip()
    for key in ("translation", "translated_text", "text", "output"):
        value = data.get(key) if isinstance(data, dict) else None
        if isinstance(value, str) and value.strip():
            return value.strip()
    if isinstance(data, dict):
        values = data.get("translations") or data.get("results") or []
        if values:
            first = values[0]
            if isinstance(first, str):
                return first.strip()
            if isinstance(first, dict):
                for key in ("translation", "translated_text", "text"):
                    value = first.get(key)
                    if isinstance(value, str) and value.strip():
                        return value.strip()
    return None


def _groq_fallback(text, target):
    language_instructions = {
        "Ga": (
            "Translate into natural contemporary Ga (Gã), the Ghanaian language "
            "spoken in Greater Accra. Do NOT translate into Twi, Ewe, Ghanaian Pidgin, "
            "or an invented African-sounding language. Preserve meaning, names, numbers, "
            "school terminology, punctuation and paragraph structure."
        ),
        "Twi": (
            "Translate into natural contemporary Ghanaian Twi (Akan). Use real Ghanaian "
            "Twi syntax and vocabulary, not a literal word-for-word English rendering. "
            "Do not substitute Ewe, Ga, Ghanaian Pidgin or generic African vocabulary."
        ),
    }
    instruction = language_instructions.get(
        target,
        f"Translate into {target}. Preserve meaning and all names, numbers and formatting.",
    )
    prompt = f"""{instruction}

This is software for a Ghanaian school management system. Translate only the text supplied.
Do not add explanations, quotation marks, labels or notes.

TEXT:
{text}
"""
    result = AIService._call_groq(
        "You are a specialist Ghanaian-language machine translation engine.",
        prompt,
        max_tokens=max(300, min(1800, len(text) * 3)),
        temperature=0.1,
        model=_setting("GROQ_TRANSLATION_MODEL", "openai/gpt-oss-120b"),
    )
    return (result or "").strip() or None


def translate_text(text, target="Twi"):
    target = _normalise_language(target)
    text = (text or "").strip()
    if not text or target == "English":
        return text
    if len(text) > MAX_TEXT_LENGTH:
        raise ValueError(f"Text is limited to {MAX_TEXT_LENGTH:,} characters.")

    protected, tokens = _protect(text)
    parts = _split_for_provider(protected)
    translated_parts = []

    for part in parts:
        translated = None
        if target == "Twi" and _setting("EDUAI_TRANSLATOR_TWI_PROVIDER", "nllb").lower() == "google":
            try:
                translated = _google_twi(part)
            except requests.RequestException:
                translated = None

        if not translated:
            try:
                translated = _nllb(part, LANGUAGES[target]["nllb"])
            except (requests.RequestException, ValueError, TypeError):
                translated = None

        if not translated:
            translated = _groq_fallback(part, target)
        if not translated:
            translated = part
        translated_parts.append(translated)

    return _restore(" ".join(translated_parts).strip(), tokens)


def translate_items(items, target="Twi"):
    """Translate DOM text-node strings while preserving item order."""
    target = _normalise_language(target)
    if target == "English":
        return list(items)

    clean = []
    total = 0
    for value in items:
        value = (value or "").strip()
        if not value:
            clean.append("")
            continue
        if len(value) > 1000:
            value = value[:1000]
        total += len(value)
        clean.append(value)
    if len(clean) > MAX_PAGE_ITEMS:
        raise ValueError(f"Page translation is limited to {MAX_PAGE_ITEMS} text items per request.")
    if total > MAX_PAGE_TEXT_LENGTH:
        raise ValueError(f"Page translation is limited to {MAX_PAGE_TEXT_LENGTH:,} characters per request.")

    # Parallel calls are important because the public NLLB endpoint is a
    # single-text API. Keep concurrency deliberately modest.
    results = [""] * len(clean)
    with ThreadPoolExecutor(max_workers=6) as pool:
        futures = {
            pool.submit(translate_text, value, target): index
            for index, value in enumerate(clean)
            if value
        }
        for future in as_completed(futures):
            index = futures[future]
            try:
                results[index] = future.result()
            except Exception:
                results[index] = clean[index]
    return results
