# Generated by Django 4.2.11 on 2026-08-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Tuition Fee, Lab Fee, Transport', max_length=150)),
                ('category_type', models.CharField(choices=[('TUITION', 'Tuition'), ('TRANSPORT', 'Transportation'), ('BOARDING', 'Boarding / Hostel'), ('BOOKS', 'Books & Stationery'), ('UNIFORM', 'Uniform'), ('EXAM', 'Examination Fee'), ('LIBRARY', 'Library Fee / Fine'), ('ACTIVITY', 'PTA / Sports / Activity'), ('ADMISSION', 'Admission / Registration'), ('ARREARS', 'Balance Brought Forward'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_recurring', models.BooleanField(default=True, help_text='True if billed every term (tuition). False for one-off charges (admission fee).')),
                ('is_optional', models.BooleanField(default=False, help_text='True if only charged when a student opts in (e.g. transport, boarding).')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='school.school')),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False, help_text='Lock once invoices have been generated from it, to protect historical accuracy.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.school')),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['-academic_term__start_date', 'school_class__grade_level__order'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=30, null=True, unique=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='UNPAID', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='school.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='finance.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.invoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('ONLINE_GATEWAY', 'Online Gateway')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('REVERSED', 'Reversed')], default='CONFIRMED', max_length=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared'), ('APPROVED', 'Approved'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='school.academicterm')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees_approved', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='finance.feestructure')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees_prepared', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='students.student')),
            ],
            options={
                'ordering': ['student__user__last_name', 'student__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('fee_per_term', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='school.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentTransportSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='finance.transportroute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('standard_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_waived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_items', to='finance.feecategory')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.studentfee')),
            ],
            options={
                'ordering': ['fee_category__category_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_items', to='school.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogisticIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistic_issuance', to='finance.invoicelineitem')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='finance.logisticitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='students.student')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waiver_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, help_text='15.00 means 15% or GHS 15, depending on type.', max_digits=10)),
                ('reason', models.CharField(help_text="e.g., 'Sibling discount', 'Headmaster's scholarship'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(blank=True, help_text='Leave blank for a standing waiver that applies every term.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to='school.academicterm')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(blank=True, help_text='Leave blank to apply this waiver to the whole invoice rather than one category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_items', to='finance.feecategory')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.feestructure')),
            ],
            options={
                'ordering': ['fee_category__category_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentFinancialLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('ARREARS', 'Arrears / Balance Brought Forward'), ('INVOICE', 'Invoice Charge'), ('PAYMENT', 'Payment'), ('WAIVER', 'Discount / Waiver'), ('CREDIT', 'Credit'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund'), ('REVERSAL', 'Payment Reversal')], max_length=30)),
                ('side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_ledger_entries', to='school.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_ledger_entries', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_ledger_entries', to='students.student')),
            ],
            options={
                'ordering': ['transaction_date', 'created_at'],
                'indexes': [models.Index(fields=['school', 'student'], name='finance_stu_school__e22793_idx'), models.Index(fields=['student', 'academic_term'], name='finance_stu_student_121f83_idx'), models.Index(fields=['entry_type'], name='finance_stu_entry_t_25ecc5_idx'), models.Index(fields=['transaction_date'], name='finance_stu_transac_49eb55_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school', 'academic_term'], name='finance_stu_school__bf1627_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'academic_term'], name='finance_stu_student_4bd63a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['status'], name='finance_stu_status_324f93_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'fee_structure'), name='unique_student_fee_structure'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='finance_pay_status_cb601d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='finance_pay_method_bcd8aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='logisticitem',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_d9b47e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'academic_term')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructureitem',
            unique_together={('fee_structure', 'fee_category')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_term', 'school_class')},
        ),
        migrations.AlterUniqueTogether(
            name='feecategory',
            unique_together={('school', 'name')},
        ),
    ]
