# Generated by Django 4.2.11 on 2026-08-28 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_school_logo'),
        ('finance', '0002_paymentreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('EXTRA_CHARGE', 'Extra Charge'), ('DISCOUNT', 'Discount'), ('REFUND', 'Refund'), ('CORRECTION', 'Correction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.feecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_adjustments', to='school.school')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.studentfee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeAddOnStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., New Student Uniform Package', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('apply_to_new_students_only', models.BooleanField(default=True, help_text='If checked, only applies to students enrolled after the term started')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_addon_structures', to='school.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_addon_structures', to='school.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'name', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='FeeAddOnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('addon_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.feeaddonstructure')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addon_items', to='finance.feecategory')),
            ],
            options={
                'ordering': ['fee_category__category_type'],
            },
        ),
    ]
