# Generated by Django 4.2.11 on 2026-08-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_enrollment_history_student_is_new_student_and_more'),
        ('school', '0002_school_logo'),
        ('finance', '0004_enrollmentfeepackage_studentfeeenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeeenrollment',
            name='enrollment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.studentenrollmenttype'),
        ),
        migrations.AddField(
            model_name='studentfeeenrollment',
            name='package_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.enrollmentfeepackage'),
        ),
        migrations.AddField(
            model_name='studentfeeenrollment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_enrollments', to='school.school'),
        ),
        migrations.AddField(
            model_name='studentfeeenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='enrollmentfeepackage',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_packages', to='school.academicterm'),
        ),
        migrations.AddField(
            model_name='enrollmentfeepackage',
            name='auto_addons',
            field=models.ManyToManyField(blank=True, related_name='enrollment_packages', to='finance.feeaddonstructure'),
        ),
        migrations.AddField(
            model_name='enrollmentfeepackage',
            name='enrollment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_packages', to='students.studentenrollmenttype'),
        ),
        migrations.AddField(
            model_name='enrollmentfeepackage',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_packages', to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='enrollmentfeepackage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_packages', to='school.school'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfeeenrollment',
            unique_together={('student', 'academic_term')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentfeepackage',
            unique_together={('school', 'enrollment_type', 'academic_term')},
        ),
    ]
