# Generated by Django 4.2.11 on 2026-08-28 19:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo'),
        ('academics', '0002_initial'),
        ('students', '0003_alter_studentenrollmenttype_code_and_more'),
        ('finance', '0005_studentfeeenrollment_enrollment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAddOnStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., New Student Uniform, Admission Fee', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('term_type', models.CharField(choices=[('ALL', 'All Terms'), ('FIRST', 'First Term Only'), ('SECOND', 'Second Term Only'), ('THIRD', 'Third Term Only'), ('CUSTOM', 'Custom Terms')], default='ALL', max_length=20)),
                ('custom_terms', models.JSONField(blank=True, default=list, help_text='List of term IDs for CUSTOM term_type')),
                ('apply_to_new_students_only', models.BooleanField(default=False, help_text='If checked, only applies to new students')),
                ('is_required', models.BooleanField(default=False, help_text='If checked, this add-on is mandatory for students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_addons', to='finance.feecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_addons', to='school.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassAddOnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_term_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('second_term_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('third_term_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.classaddonstructure')),
                ('grade_level', models.ForeignKey(blank=True, help_text='Specific grade level (e.g., KG 1, JHS 1)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_items', to='students.gradelevel')),
                ('school_class', models.ForeignKey(blank=True, help_text='Specific class (e.g., KG 1A, JHS 1A)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_items', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['addon_structure__name'],
                'unique_together': {('addon_structure', 'grade_level', 'school_class')},
            },
        ),
    ]
