# Generated by Django 4.2.11 on 2026-08-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_classaddonstructure_classaddonitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classaddonitem',
            name='first_term_amount',
        ),
        migrations.RemoveField(
            model_name='classaddonitem',
            name='second_term_amount',
        ),
        migrations.RemoveField(
            model_name='classaddonitem',
            name='third_term_amount',
        ),
    ]
