# Generated by Django 4.2.11 on 2026-08-30 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo'),
        ('finance', '0008_classaddonitem_first_term_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classaddonitem',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this item belongs to (auto-populated from addon_structure)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_addon_items', to='school.school'),
        ),
    ]
