# Generated by Django 4.2.11 on 2026-08-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_classaddonitem_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classaddonstructure',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='If checked, this add-on can be opted in/out by parent'),
        ),
        migrations.AlterField(
            model_name='classaddonstructure',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If checked, this add-on is mandatory for applicable students'),
        ),
    ]
