# Generated by Django 4.2.11 on 2026-08-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_classaddonstructure_is_optional_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classaddonitem',
            unique_together=set(),
        ),
    ]
