# Generated by Django 4.2.11 on 2026-08-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='staff',
            field=models.ForeignKey(help_text='The staff member whose actual salary this structure defines.', on_delete=django.db.models.deletion.PROTECT, related_name='salary_structures', to='staff.staffprofile'),
        ),
    ]
