# Generated by Django 4.2.11 on 2026-08-25 07:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo'),
        ('staff', '0002_alter_salarystructure_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom amount for this grade (leave blank to use the default allowance amount)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_percentage', models.BooleanField(default=False, help_text='If True, amount is a percentage of basic salary')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['staff_grade__level', 'allowance__name'],
            },
        ),
        migrations.AlterField(
            model_name='staffallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom amount for this staff member (overrides the default)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='staffallowance',
            index=models.Index(fields=['staff', 'allowance'], name='staff_staff_staff_i_52def9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffallowance',
            index=models.Index(fields=['staff', 'is_active'], name='staff_staff_staff_i_118c47_idx'),
        ),
        migrations.AddField(
            model_name='gradeallowance',
            name='allowance',
            field=models.ForeignKey(help_text='The allowance to assign to this grade', on_delete=django.db.models.deletion.CASCADE, related_name='grade_allowances', to='staff.allowance'),
        ),
        migrations.AddField(
            model_name='gradeallowance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_allowances', to='school.school'),
        ),
        migrations.AddField(
            model_name='gradeallowance',
            name='staff_grade',
            field=models.ForeignKey(help_text='The staff grade that receives this allowance', on_delete=django.db.models.deletion.CASCADE, related_name='grade_allowances', to='staff.staffgrade'),
        ),
        migrations.AddIndex(
            model_name='gradeallowance',
            index=models.Index(fields=['staff_grade', 'allowance'], name='staff_grade_staff_g_3ecd81_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeallowance',
            index=models.Index(fields=['staff_grade', 'is_active'], name='staff_grade_staff_g_cbc6a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeallowance',
            unique_together={('staff_grade', 'allowance')},
        ),
    ]
