# Generated by Django 4.2.11 on 2026-08-25 10:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_gradeallowance_alter_staffallowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradeallowance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gradeallowance',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='gradeallowance',
            name='school',
        ),
        migrations.RemoveField(
            model_name='gradeallowance',
            name='staff_grade',
        ),
        migrations.AlterModelOptions(
            name='staffallowance',
            options={'ordering': ['staff__user__last_name', 'staff__user__first_name', 'allowance__name']},
        ),
        migrations.RemoveIndex(
            model_name='staffallowance',
            name='staff_staff_staff_i_52def9_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffallowance',
            name='staff_staff_staff_i_118c47_idx',
        ),
        migrations.AlterUniqueTogether(
            name='staffallowance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='staffallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional staff-specific amount. Leave blank to use the allowance default amount.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='staffallowance',
            index=models.Index(fields=['school', 'staff', 'is_active'], name='staff_allowance_active_idx'),
        ),
        migrations.AddIndex(
            model_name='staffallowance',
            index=models.Index(fields=['school', 'allowance', 'is_active'], name='allowance_staff_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffallowance',
            constraint=models.UniqueConstraint(fields=('staff', 'allowance'), name='unique_staff_allowance'),
        ),
        migrations.DeleteModel(
            name='GradeAllowance',
        ),
    ]
