# Generated by Django 4.2.24 on 2026-09-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_restore_gradeallowance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gradeallowance',
            new_name='staff_grade_staff_g_3ecd81_idx',
            old_name='staff_grade_allowance_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeallowance',
            new_name='staff_grade_staff_g_cbc6a2_idx',
            old_name='staff_grade_active_idx',
        ),
    ]
