# Generated by Django 4.2.11 on 2026-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a logo for your school (recommended size: 200x200px)', null=True, upload_to='school_logos/'),
        ),
    ]
