# Generated by Django 4.2.11 on 2026-08-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('overdue_balance_enabled', models.BooleanField(default=True)),
                ('timetable_update_enabled', models.BooleanField(default=True)),
                ('grade_release_enabled', models.BooleanField(default=True)),
                ('announcement_enabled', models.BooleanField(default=True)),
                ('attendance_alert_enabled', models.BooleanField(default=True)),
                ('promotion_result_enabled', models.BooleanField(default=True)),
                ('leave_approval_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='school.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Notification Preferences',
                'unique_together': {('school', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('OVERDUE_BALANCE', 'Overdue Balance'), ('TIMETABLE_UPDATE', 'Timetable Update'), ('GRADE_RELEASE', 'Grade Release'), ('ANNOUNCEMENT', 'Announcement'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('ATTENDANCE_ALERT', 'Attendance Alert'), ('PROMOTION_RESULT', 'Promotion Result'), ('SYSTEM_ALERT', 'System Alert'), ('LEAVE_APPROVAL', 'Leave Approval'), ('STAFF_REMINDER', 'Staff Reminder')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In-App'), ('BOTH', 'Email & SMS'), ('ALL', 'All Channels')], default='EMAIL', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference to related object (invoice_id, leave_id, etc.)', max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (invoice, leave, etc.)', max_length=50, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='school.school')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='communicati_recipie_ffbd62_idx'), models.Index(fields=['school', 'created_at'], name='communicati_school__da19d0_idx'), models.Index(fields=['category'], name='communicati_categor_c3933d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g., Parent-Teacher Association Meeting', max_length=255)),
                ('content', models.TextField(help_text='Detailed announcement content')),
                ('summary', models.CharField(blank=True, help_text='Short summary for preview', max_length=500, null=True)),
                ('audience', models.CharField(choices=[('ALL', 'All Personnel & Parents'), ('TEACHERS', 'Faculty & Staff Only'), ('PARENTS', 'Parents Only'), ('STUDENTS', 'Students Only'), ('STAFF', 'Staff Only'), ('ADMIN', 'Administrators Only')], default='ALL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When to publish this announcement')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this announcement expires', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.school')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_at', '-created_at'],
                'indexes': [models.Index(fields=['school', 'is_published'], name='communicati_school__59a95a_idx'), models.Index(fields=['school', 'audience'], name='communicati_school__0cefee_idx'), models.Index(fields=['publish_at', 'expires_at'], name='communicati_publish_6f984b_idx')],
            },
        ),
    ]
