# Generated by Django 4.2.24 on 2026-09-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_mysql_safe_notification_reference_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationlog',
            name='uniq_notification_reference_per_recipient',
        ),
    ]
