# Generated by Django 4.2.11 on 2026-08-20 02:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_core', models.BooleanField(default=False, help_text='Is this a core/compulsory subject?')),
                ('periods_per_week', models.PositiveIntegerField(default=4, help_text='Default periods per week for this subject in this class')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['school_class__name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., '2025 Academic Year Promotion'", max_length=200)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('promoted', models.PositiveIntegerField(default=0)),
                ('conditional', models.PositiveIntegerField(default=0)),
                ('repeated', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=15)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion_mode', models.CharField(choices=[('AUTO', 'Automatic Promotion'), ('MANUAL', 'Manual Promotion'), ('HYBRID', 'Hybrid (Auto with Manual Override)')], default='AUTO', max_length=10)),
                ('minimum_passing_grade', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum grade percentage to pass a subject', max_digits=5)),
                ('minimum_subjects_to_pass', models.PositiveIntegerField(default=0, help_text='Minimum number of subjects a student must pass to be promoted (0 = all subjects)')),
                ('minimum_overall_average', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum overall average to be promoted', max_digits=5)),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance percentage required for promotion', max_digits=5)),
                ('allow_conditional_promotion', models.BooleanField(default=False, help_text='Allow conditional promotion for students who narrowly miss requirements')),
                ('max_conditional_subjects', models.PositiveIntegerField(default=2, help_text='Maximum number of subjects a student can fail and still be conditionally promoted')),
                ('evaluation_term_sequence', models.PositiveIntegerField(default=3, help_text="Which term's results to evaluate (1, 2, 3 - usually 3 for third term)")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['from_grade_level__order', 'to_grade_level__order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Room 302, Chemistry Lab', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('is_lab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Basic 1, JHS 2 Gold', max_length=100)),
                ('student_count', models.PositiveIntegerField(default=0, editable=False)),
                ('uses_single_class_teacher', models.BooleanField(blank=True, default=None, help_text="Common in Ghanaian Nursery/KG and lower Primary classes: one class teacher delivers every subject, rather than a different subject teacher per period. When True, assigning a class teacher (see homeroom_teacher) automatically creates the underlying per-subject TeacherAssignment rows the timetabler needs -- no manual per-subject assignment required. Left as None until first saved, at which point it defaults from the grade level's GES stage (True for KG/Primary, False for JHS/SHS) -- but a school can override it per class either way.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'School Classes',
                'ordering': ['grade_level__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, help_text='Overall average at time of promotion', max_digits=5, null=True)),
                ('subjects_passed', models.PositiveIntegerField(default=0, help_text='Number of subjects passed')),
                ('subjects_failed', models.PositiveIntegerField(default=0, help_text='Number of subjects failed')),
                ('failed_subjects', models.JSONField(default=list, help_text='List of failed subject names')),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Attendance percentage at time of promotion', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PROMOTED', 'Promoted'), ('CONDITIONAL', 'Conditionally Promoted'), ('REPEATED', 'Repeated'), ('EXPELLED', 'Expelled'), ('TRANSFERRED', 'Transferred')], default='PENDING', max_length=15)),
                ('is_automatic', models.BooleanField(default=False, help_text='Was this promotion automatically processed?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Mathematics, Integrated Science', max_length=150)),
                ('code', models.CharField(blank=True, editable=False, max_length=50)),
                ('requires_lab', models.BooleanField(default=False, help_text='If true, the timetabler will only place this subject in a lab-equipped room.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periods_per_week', models.PositiveIntegerField(default=4, help_text='Number of periods per week for this subject in this class')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary teacher for this class?')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['school_class__name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['school_class__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_periods', models.PositiveIntegerField(default=0, help_text='Total periods assigned to this teacher this term')),
                ('max_periods', models.PositiveIntegerField(default=25, help_text='Maximum periods allowed per week for this teacher')),
                ('workload_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of max workload used', max_digits=5)),
                ('subject_breakdown', models.JSONField(default=dict, help_text="Breakdown of subjects taught: {'subject_name': periods_count, ...}")),
                ('class_breakdown', models.JSONField(default=dict, help_text="Breakdown of classes taught: {'class_name': periods_count, ...}")),
                ('is_overloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-workload_percentage'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('period_index', models.PositiveSmallIntegerField(help_text='1 = first period of the day, 2 = second, etc.')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day', 'period_index'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('RUNNING', 'Generating'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('fitness_score', models.FloatField(default=0.0)),
                ('hard_conflicts', models.PositiveIntegerField(default=0)),
                ('soft_conflicts', models.PositiveIntegerField(default=0)),
                ('generations_run', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False, help_text='The one timetable actively shown to teachers/students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_lab', models.BooleanField(default=False, help_text='Is this a lab session?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.room')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subject')),
            ],
            options={
                'ordering': ['school_class__name', 'timeslot__day', 'timeslot__period_index'],
            },
        ),
    ]
