# Generated by Django 4.2.11 on 2026-08-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.timeslot'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.academicterm'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.school'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherworkload',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_workloads', to='school.academicterm'),
        ),
        migrations.AddField(
            model_name='teacherworkload',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_workloads', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherworkload',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homerooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_teachers', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='from_grade_level',
            field=models.ForeignKey(help_text='Grade level being promoted FROM', on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='students.gradelevel'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='from_school_class',
            field=models.ForeignKey(blank=True, help_text='Class being promoted FROM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='promotion_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='academics.promotionbatch'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions', to='school.school'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='to_grade_level',
            field=models.ForeignKey(help_text='Grade level being promoted TO', on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='students.gradelevel'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='to_school_class',
            field=models.ForeignKey(blank=True, help_text='Class being promoted TO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='students.gradelevel'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homerooms', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.school'),
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='school.school'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='from_grade_level',
            field=models.ForeignKey(help_text='The grade level students are being promoted FROM', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_from', to='students.gradelevel'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='school.school'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='to_grade_level',
            field=models.ForeignKey(help_text='The grade level students are being promoted TO', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_to', to='students.gradelevel'),
        ),
        migrations.AddField(
            model_name='promotionbatch',
            name='academic_term',
            field=models.ForeignKey(help_text='The term being evaluated for promotion', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_batches', to='school.academicterm'),
        ),
        migrations.AddField(
            model_name='promotionbatch',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_batches', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='promotionbatch',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_promotion_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionbatch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_batches', to='school.school'),
        ),
        migrations.AddField(
            model_name='classsubjectrequirement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='school.school'),
        ),
        migrations.AddField(
            model_name='classsubjectrequirement',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='classsubjectrequirement',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requirements', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='school.school'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('timetable', 'school_class', 'timeslot')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('school', 'day', 'period_index')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherworkload',
            unique_together={('teacher', 'academic_term')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherclassassignment',
            unique_together={('school_class', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'school_class', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'grade_level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='promotionrule',
            unique_together={('school', 'from_grade_level', 'to_grade_level')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectrequirement',
            unique_together={('school_class', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('school_class', 'subject')},
        ),
    ]
