# Generated by Django 4.2.24 on 2026-09-23 00:01

import academics.timetable_configuration_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_timetableconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableconfiguration',
            name='blocks',
            field=models.JSONField(default=academics.timetable_configuration_model.default_schedule_blocks),
        ),
        migrations.AlterField(
            model_name='timetableconfiguration',
            name='days',
            field=models.JSONField(default=academics.timetable_configuration_model.default_schedule_days),
        ),
    ]
