# Generated by Django 4.2.24
# T4.1 - Explicit Timetable Schedule Blocks

import uuid

from django.db import migrations, models
import django.db.models.deletion


def copy_json_blocks_to_rows(apps, schema_editor):
    """
    Convert existing JSON schedule blocks stored on
    TimetableConfiguration into explicit TimetableScheduleBlock rows.

    Existing configuration data is preserved.
    Duplicate rows are avoided.
    """
    TimetableConfiguration = apps.get_model(
        "academics",
        "TimetableConfiguration",
    )

    TimetableScheduleBlock = apps.get_model(
        "academics",
        "TimetableScheduleBlock",
    )

    for configuration in TimetableConfiguration.objects.all():
        blocks = configuration.blocks or []

        if not isinstance(blocks, list):
            continue

        for index, block in enumerate(blocks):
            if not isinstance(block, dict):
                continue

            block_type = (
                block.get("block_type")
                or block.get("type")
                or "OTHER"
            )

            block_type = str(block_type).upper().strip()

            valid_types = {
                "ASSEMBLY",
                "BREAK",
                "LUNCH",
                "ACTIVITY",
                "CLUB",
                "OTHER",
            }

            if block_type not in valid_types:
                block_type = "OTHER"

            label = (
                block.get("label")
                or block.get("name")
                or block_type.title()
            )

            try:
                after_period = int(
                    block.get("after_period", 2) or 2
                )
            except (TypeError, ValueError):
                after_period = 2

            try:
                minutes = int(
                    block.get("minutes", 30) or 30
                )
            except (TypeError, ValueError):
                minutes = 30

            try:
                sort_order = int(
                    block.get("sort_order", index) or index
                )
            except (TypeError, ValueError):
                sort_order = index

            day = block.get("day") or None

            exists = TimetableScheduleBlock.objects.filter(
                configuration=configuration,
                day=day,
                block_type=block_type,
                label=str(label),
                after_period=after_period,
            ).exists()

            if exists:
                continue

            TimetableScheduleBlock.objects.create(
                configuration=configuration,
                day=day,
                block_type=block_type,
                label=str(label)[:60],
                after_period=after_period,
                minutes=minutes,
                is_active=block.get("is_active", True),
                sort_order=sort_order,
            )


def reverse_rows_to_json(apps, schema_editor):
    """
    Restore explicit schedule blocks to the legacy JSON field
    if this migration is reversed.
    """
    TimetableConfiguration = apps.get_model(
        "academics",
        "TimetableConfiguration",
    )

    TimetableScheduleBlock = apps.get_model(
        "academics",
        "TimetableScheduleBlock",
    )

    for configuration in TimetableConfiguration.objects.all():

        rows = TimetableScheduleBlock.objects.filter(
            configuration=configuration
        ).order_by(
            "day",
            "after_period",
            "sort_order",
            "label",
        )

        blocks = []

        for row in rows:
            blocks.append(
                {
                    "day": row.day,
                    "block_type": row.block_type,
                    "label": row.label,
                    "after_period": row.after_period,
                    "minutes": row.minutes,
                    "is_active": row.is_active,
                    "sort_order": row.sort_order,
                }
            )

        configuration.blocks = blocks
        configuration.save(update_fields=["blocks"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0004_alter_timetableconfiguration_blocks_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableScheduleBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_blocks",
                        to="academics.timetableconfiguration",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        max_length=3,
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                        ],
                        null=True,
                        blank=True,
                        help_text=(
                            "Leave blank to apply this block to every "
                            "configured school day."
                        ),
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("ASSEMBLY", "Assembly / Devotion"),
                            ("BREAK", "Break"),
                            ("LUNCH", "Lunch"),
                            ("ACTIVITY", "Activity"),
                            ("CLUB", "Club / Enrichment"),
                            ("OTHER", "Other"),
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=60),
                ),
                (
                    "after_period",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text=(
                            "0 = before Period 1; otherwise the block "
                            "starts after this teaching period."
                        ),
                    ),
                ),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "day",
                    "after_period",
                    "sort_order",
                    "label",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="timetablescheduleblock",
            index=models.Index(
                fields=[
                    "configuration",
                    "day",
                    "after_period",
                ],
                name="academics_ts_config_day_after_idx",
            ),
        ),
        migrations.RunPython(
            copy_json_blocks_to_rows,
            reverse_rows_to_json,
        ),
    ]