# Generated by Django 4.2.24 on 2026-09-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetablescheduleblock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetablescheduleblock',
            new_name='academics_t_configu_688a4f_idx',
            old_name='academics_ts_config_day_after_idx',
        ),
    ]
