# Generated by Django 4.2.24 on 2026-10-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_staffattendance_stafffaceprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='attendance__school__d91bbe_idx',
            old_name='attendance_sch_date_idx',
        ),
        migrations.RenameIndex(
            model_name='staffattendance',
            new_name='attendance__staff_i_d77b2d_idx',
            old_name='attendance_stf_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stafffaceprofile',
            new_name='attendance__school__a5322e_idx',
            old_name='attendance_sch_active_idx',
        ),
    ]
